services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: hikari
      POSTGRES_PASSWORD: hikari
      POSTGRES_DB: hikari
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    ports:
      - '6379:6379'

volumes:
  db-data:
